repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        exclude: .+.patch$
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ['--unsafe', '--allow-multiple-documents']
        exclude: templates\/.+.yaml$|pnpm-lock.yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=750']
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
    -   id: terraform_fmt